# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('insTm', models.DateTimeField(auto_now_add=True)),
                ('updTm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('createUserId', models.IntegerField()),
                ('insTm', models.DateTimeField(auto_now_add=True)),
                ('updTm', models.DateTimeField(auto_now=True)),
                ('appealPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buono.AppealPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insTm', models.DateTimeField(auto_now_add=True)),
                ('updTm', models.DateTimeField(auto_now=True)),
                ('appealPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buono.AppealPoint')),
            ],
        ),
        migrations.AddField(
            model_name='appealpoint',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buono.Generation'),
        ),
        migrations.AddField(
            model_name='appealpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
