# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='typeCd',
            field=models.CharField(max_length=1),
            preserve_default=False,
        ),
    ]
