# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buono', '0003_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='detail',
            field=models.TextField(default=''),
        ),
    ]
